### ISSUE TITLE
[Bug][Obsidian Insider 1.2.0] Plugin broken

### ISSUE THREAD

**Issue by Lisandra-dev** [aidenlx/alx-folder-note#102]
The new version of Obsidian (1.2.0) changed the internal of the explorer. In consequence, it broke the plugin.

![image](https://user-images.githubusercontent.com/30244939/228970163-90a17d14-b8b9-48a7-8110-bc8112046c8a.png)

I'm stupid and forgot to take a screenshot of the log. 
Maybe someone can help us to debug the plugin?

**Comment by namtrah** [comment]
I can confirm the fixed build in #103 works! Just don't replace your data.json.
