### ISSUE TITLE
Clicking on folder does not open folder note

### ISSUE THREAD

**Issue by fncll** [aidenlx/alx-folder-note#104]
Clicking on the folder in the file tree, though it is underlined and appears that it should work, collapses/expands the folder rather than showing the folder note. I have no file tree related plugins installed and am using the default theme. How can I troubleshoot this?

I am running Obsidian 1.2.0 btw, which could be the problem?

**Comment by JeppeKlitgaard** [comment]
I am having the same problem after updating to Obsidian `1.2.x`
