### ISSUE TITLE
Broken on Obsidian v1.2.7

### ISSUE THREAD

**Issue by steve-hadley** [aidenlx/alx-folder-note#107]
The latest Obsidian update v1.2.7 seems to have broken this plugin, clicking on underlined folders no longer opens the folder note.  Steps to reproduce are just updating to v1.2.7 and then attempting to use the plugin.

**Comment by colintedford** [comment]
Also seen on the new mobile 1.4.4 (iOS/iPadOS).

**Comment by MatteoAlberghini** [comment]
Should be solved by #103

**Comment by martyfmelb** [comment]
I am experiencing the same issue on Obsidian Android latest (v1.4.4) and Obsidian Windows latest (v1.2.7). Clicking an underlined folder just toggles it between expanded and collapsed (showing / not showing its children).

My current workaround is to pull up the context menu for an underlined folder and choose "Open Folder Note".
