### ISSUE TITLE
[feature request] Allow templater templates for folder note creation

### ISSUE THREAD

**Issue by vorpalvorpal** [aidenlx/alx-folder-note#117]
Would it be possible to call a templater template on creation of a folder note?

**Comment by FynnFreyer** [comment]
You can already do that. It's just not folder note specific, but for every file created in your vault.

![Set "Trigger Templater on new file creation"](https://github.com/aidenlx/alx-folder-note/assets/24855836/18ef4041-5951-4983-943e-d341355ac774)

Set "Trigger Templater on new file creation" in the Templater settings and add your templater code to the "Folder Note Template" in the Folder Note settings.

I'm using this for example: `<% tp.file.include("[[Default Frontmatter]]") %>`
This allows me to use a dedicated file where I can edit and put it under version control more easily.

As noted in the settings: this runs code whenever a file is created in your vault, which is a serious risk on untrusted inputs. But I assume you're a grown adult and know the risks ;)

**Comment by vorpalvorpal** [comment]
Awesome. I didn't realise it would be so simple.
