### ISSUE TITLE
Feature: Mobile Support

### ISSUE THREAD

**Issue by Mara-Li** [aidenlx/alx-folder-note#12]
I wanna know why the plugin doesn't work on mobile. It is because of code mirror 6 ? The plugin doesn't want to activate and i think it's a pitu because it works great on PC!

**Comment by aidenlx** [comment]
It hasn't been tested yet. If you want to try if it works, you can set `isDesktopOnly` in `manifest.json` to true to see if the plugin works.

**Comment by VKondakoff** [comment]
Please, change the `"isDesktopOnly":` to `false` by default. Without this change the plugin stops working on mobile after each update. Thanks!
