### ISSUE TITLE
CSS global pollution

### ISSUE THREAD

**Issue by phibr0** [aidenlx/alx-folder-note#14]
When enabling your Plugin all Styles are changed. For example in Darkmode some of the Text remains black:

![image](https://user-images.githubusercontent.com/59741989/128638998-b1282c31-cad8-4c8e-8eb7-cf266b0f4e6c.png)

**Comment by aidenlx** [comment]
Related: https://ant.design/docs/react/customize-theme#How-to-avoid-modifying-global-styles
