### ISSUE TITLE
Consider making compatible with Zootelkeeper

### ISSUE THREAD

**Issue by brimwats** [aidenlx/alx-folder-note#16]
See: https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin/issues/6

**Comment by aidenlx** [comment]
I'm not getting this, what kind of conflict is there between two plugins now? can you make a small demo in a simple, separate vault, and even better, upload the vault as zip to here.

**Comment by brimwats** [comment]
this may be my error, I think it is prob something that has to be done in zootelkeeper before here!
