### ISSUE TITLE
Open file in `folderv` with modifier also open it in original leaf

### ISSUE THREAD

**Issue by aidenlx** [aidenlx/alx-folder-note#20]
![59508c15fb8e5891096a37455280fd1f444c90fa](https://user-images.githubusercontent.com/31102694/130776194-720c5c2f-a223-4eaa-9c21-0dd7b10f0916.gif)

https://forum.obsidian.md/t/folder-as-markdown-note/2902/87?u=aidenlx

**Comment by JoseEchave** [comment]
Following
