### ISSUE TITLE
Weird File Naming Bug

### ISSUE THREAD

**Issue by brimwats** [aidenlx/alx-folder-note#26]
For some reason lately when I crtl+click Folder Note is creating a file named like `11` where it should be like `11. LIBR 554—Database Design Overview `

![image](https://user-images.githubusercontent.com/49103046/133533430-1c1a23d6-c374-4453-884b-4b0b7ebaebb0.png)

also sometimes it is posting YAML, other times it is not

![image](https://user-images.githubusercontent.com/49103046/133533467-53614f84-488a-43c8-8891-883ed5aa6c78.png)

Here's my settings 
![image](https://user-images.githubusercontent.com/49103046/133533501-93bb833b-55cf-4391-9676-d7170c514d96.png)
![image](https://user-images.githubusercontent.com/49103046/133533504-a5d21743-f00d-404c-b0f9-7ea860a8bcae.png)

**Comment by aidenlx** [comment]
Update folder-note-core to the latest should fix this problm
