### ISSUE TITLE
[Bug] Folder Note breaks when workspace is changed

### ISSUE THREAD

**Issue by WychWitch** [aidenlx/alx-folder-note#29]
I've been having a weird issue; whenever I open obsidian the folder note plugin seems as though it fails to start. The folders with folder notes are no longer clickable, and the notes themselves are in the folder as if the plugin isn't installed. Its only after disabling and re-enabling it in settings that it will "turn on" and work as intended.

I'm not sure what may be the issue? Maybe some plugin incompatability? This is on windows 10 on v0.12.15 of Obsidian.

If there's any debugging I can do that will help I'll gladly do it! It's not the worst bug in the world, but it's a bit annoying to have to disable and re -enable each time

**Comment by WychWitch** [comment]
OH I see, its not a problem with that plugin at all,! Not specifically anyways. Changing workspaces is what breaks it, doing so with vanilla obsidian does the same thing, requiring the plugin to be reloaded. Attached is the log, and I'll rename the thread
[obsidian.md-1634419416775.log](https://github.com/aidenlx/alx-folder-note/files/7358275/obsidian.md-1634419416775.log)

**Comment by thomasvs** [comment]
I have the same bug.  Glad I checked previous issues first.

I notice the same behavior in a different plugin, the note count; filed that there: https://github.com/ozntel/file-explorer-note-count/issues/8

Just a guess - maybe changing workspaces creates a new display object backing the file explorer which doesn't get the right callbacks attached, and both plugins are still updating the original display object that is no longer being shown?
