### ISSUE TITLE
Issue: Foldererv does not work with live preview mode

### ISSUE THREAD

**Issue by brimwats** [aidenlx/alx-folder-note#33]
According to Licat https://discord.com/channels/686053708261228577/716028884885307432/911327832481886269

foldererv needs to use registerCodeBlockPostProcessor

**Comment by aidenlx** [comment]
It's already working

https://user-images.githubusercontent.com/31102694/142719340-09918a2c-ce69-4b50-b51e-6080560f54ff.mp4
