### ISSUE TITLE
希望可以有一个「每当新建文件夹，就为其建立一个文件夹笔记」的选项开关

### ISSUE THREAD

**Issue by LoneFireBlossom** [aidenlx/alx-folder-note#37]
如标题所说。我基本上全都会做注释的，所以希望全都有相应的笔记。

顺带，已知在obsidian的md文件中，对于一个没有建立笔记的双向链接，点一下可以生成对应的笔记；
如果插件还能实现，「我按住某些修饰键如command，就可以生成对应的文件夹和文件夹笔记」，就更好了。
但是感觉这个似乎实现不了……

**Comment by LoneFireBlossom** [comment]
虽然是另一个建议但我不是很需要就不新建一个issue了。

现在obsidian的文件管理中，把文件拖动到文件夹上就可以改变文件的存放路径。
插件是否可以做到，「把A.md文件拖动到B.md文件上，就可以新建一个B文件夹，并把A文件放到B文件夹目录下」？感觉这个对一些人应该也有用。

**Comment by aidenlx** [comment]
这个issue跟 #5 重复了我就先关掉了，后面那个我帮你单独开个FR
