### ISSUE TITLE
Unable to link existing notes to folder note.

### ISSUE THREAD

**Issue by kkYrusobad** [aidenlx/alx-folder-note#47]
I have multiple notes in place already and want to link them to the folder note, but I am unable to do so. 
I read the wiki which insinuates that there is a command something like `link to parent folder note` but the command palette is unable to find such command and returns nothing.

**Comment by aidenlx** [comment]
The command is meant to convert a regular note to the folder note of the parent folder. To link files to folder note, you can use regular internal links.

**Comment by kkYrusobad** [comment]
Is there any way to automatically create links to files when created?
I am doing it manually for a while now, it's inefficient. Any way to automate?
