### ISSUE TITLE
Hide index file from graph view

### ISSUE THREAD

**Issue by universvm** [aidenlx/alx-folder-note#48]
Hi, 

I think there should be an option to hide the index file from the graph view. I tried using:

```
file:-"_about_"
```

But I think I'm doing something wrong. Essentially, without a solution, the graph view is rather useless if you have lots of folder (see attached).
<img width="376" alt="Screenshot 2021-12-27 at 14 33 23" src="https://user-images.githubusercontent.com/17524568/147477341-9319877b-c5f5-4d2e-a7e9-c3e5dec4a702.png">

Let me know if you have a solution for this

**Comment by aidenlx** [comment]
I think zoottelkeeper is aiming to solve this by maintaining a list of internal links to children of folder in index note: https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin

**Comment by universvm** [comment]
Right, I have no idea how that plugin solves the issue. Maybe in the future allow dialogue instead of closing the issue.

One of the main reason to use Obsidian over other apps is the graph view and this plugin makes it cluttered (ie. useless).

My current workaround is to add the filter `-_about_` in case some people find this issue from google.
