### ISSUE TITLE
View Subfolders

### ISSUE THREAD

**Issue by MechatronPrime1** [aidenlx/alx-folder-note#50]
Hi. 

Is there a way to view subfolders in the folder note? 

Using xpgo addon, I place the note outside the folder and it shows up.  But its starting to get a bit annoying because the note appear on the left bar until I open the folder note, then it disappears.

Thanks.

**Comment by aidenlx** [comment]
I'm not sure what you mean, do you have trouble with `folderv` code blocks or file explorer? can you add a screenshot about what you are expecting to achieve?

**Comment by dybrawin** [comment]
Hey,

I was having the same question/request.
Here's a screenshot
![image](https://user-images.githubusercontent.com/34630600/155988287-d582c649-d487-4443-b053-f73cf966d201.png)

It seems more like a question or proposition on __folderv__

**Comment by aidenlx** [comment]
it's not supported yet, which is tracked [here](https://github.com/aidenlx/alx-folder-note/issues/13)

**Comment by TristGit** [comment]
@aidenlx Was something ever done with this..? Your tracked link isnt available anymore.
