### ISSUE TITLE
Failed to initalize: folder-note-core plugin not enabled

### ISSUE THREAD

**Issue by Volker-brdb** [aidenlx/alx-folder-note#51]
Can't activated alx-folder-note because it says that folder-note core plugin is not enabled. 
But it is enabled

![2022-01-07 09_37_42-WISSENS-DB - Obsidian v0 13 19](https://user-images.githubusercontent.com/72230479/148516531-be2a7d85-dbd5-4d6a-8a07-6b150975e4c0.png)

![2022-01-07 09_43_12-WISSENS-DB - Obsidian v0 13 19](https://user-images.githubusercontent.com/72230479/148517119-5f2f128a-b961-4d0b-8290-c421c661b95e.png)

**Comment by aidenlx** [comment]
Does disable and enable alx-folder-note in the plugin setting help?

**Comment by Volker-brdb** [comment]
Nope, unfortunatley not.

AidenLxs-Folder Note Version 0.12.3
Folder Note Version 0.7.3
Obsidian Version 0.13.19
Windows10
Appeares on two diffrent PCs with two diffrent Obsidian Vaults

**Comment by aidenlx** [comment]
Wait, you should install Folder Note **Core** , not Folder Note 😂

**Comment by Volker-brdb** [comment]
👀 ...oh yeah 😂  
Great, thank you
