### ISSUE TITLE
Advice on clicking on a folder in a directory

### ISSUE THREAD

**Issue by JamboPanette** [aidenlx/alx-folder-note#52]
Currently, for folders with folder notes, the click effect is to open the folder notes.Considering that the indicator for expanding the folder is on the far left, it is inconvenient to click and it is often mistakenly touched. I hope to add the option of clicking on the folder to directly open the subdirectory of the folder.

**Comment by ndegroot** [comment]
Nice plugin!
On IOS (iPad) it's a bigger problem: the indicator isn't even visable. Maybe the UI action 'click = show folder note' can be removed or made optional in the settings. You can allways use a command to see the folder note
