### ISSUE TITLE
Add `is-active` class to `div.nav-folder-title` when folder note is active

### ISSUE THREAD

**Issue by JeppeKlitgaard** [aidenlx/alx-folder-note#53]
Hey Aiden,

First of all, thank you for an amazing plugin!

I think it would make sense to style the folder as 'active' in a similar way to how Obsidian styles `nav-files`, such that a `is-active` class is added.

This would allow the user to more easily see that the folder note is open.

![image](https://user-images.githubusercontent.com/1814611/148849443-0dec4138-df66-4eed-b6af-81f4ff423843.png)

**Comment by samwarnick** [comment]
Was just thinking this morning that this would be a great feature! I ran into a weird edge case: if my folder note is a kanban board using [obsidian-kanban](https://github.com/mgmeyers/obsidian-kanban), then `is-active` is not added. I can make a repo with a sample vault if that would be helpful.
