### ISSUE TITLE
Request: Allow for mobile click on folder to open folder instead of folder note

### ISSUE THREAD

**Issue by lukthony** [aidenlx/alx-folder-note#56]
On mobile, clicking on the icon next to the folder to open it is much harder than on Desktop, as it is very small and not that large of a touch target. This plug-in removes the ability to click on the folder name to open it when that folder has a folder note. I would prefer if it were possible to disable that functionality(instead clicking on the arrow symbol to open the folder note).

**Comment by Obadiahcruz** [comment]
i think it would be best to add a setting for this. i have collapse icons hidden and i cant configure opening folders by having a click. maybe you can enable modifiers or double clicks to open different things @aidenlx
