### ISSUE TITLE
Can you increase the size of the click area to open folder notes so that it is over the folder name and the folder icon? 

### ISSUE THREAD

**Issue by Madmaxneo** [aidenlx/alx-folder-note#58]
I recently had an issue where this plugin would not work at all, even after reloading the plugins or restarting the program. I had to uninstall the plugin and reinstall it to get it to work. 
Now though I noticed that the click area on some of the folders and all of the folder notes is to the far right in the blank area next to the folder name, which is not intuitive, 
Notice that I said some folders are like that where some aren't. If the folder has  the _greater than symbol_ ">" pointing to the right like an arrow then you can't click on the folder to expand it but have to click to the right of that symbol. But the folders that do not have that symbol you can just click on the folder to expand it. 

Is it possible to fix this issue?

**Comment by aidenlx** [comment]
it will be fixed in next version, [this commit](https://github.com/aidenlx/alx-folder-note/commit/35e8e153e071949f6315ae384f38496f2eb31a24) to be exact

**Comment by aidenlx** [comment]
available in v0.15.0
