### ISSUE TITLE
Click folder doesn't open folder note (Release 0.13.1 )

### ISSUE THREAD

**Issue by anselmwang** [aidenlx/alx-folder-note#60]
The old folder note plugin is out of maintenance for one year. Thanks for creating this plugin!

# Behavior
Old version works, has a ">" next to the folder name. Here is the old version info
```
  "version": "0.12.3",
  "minAppVersion": "0.12.5",
```
New version doesn't.

# A small suggestion
The release name is 0.13.1, while in the manifest.json has following information.
```
  "version": "1.0.0",
  "minAppVersion": "0.12.5",
```
I am confused when reporting this issue. Have to look back several times to ensure I provide the correct version information
Could you make them consistent?

# Environment
OS: Windows 10
Obsidian: v0.13.23
Plugin version: 
```
  "version": "1.0.0",
  "minAppVersion": "0.12.5",
```

**Comment by aidenlx** [comment]
Are you sure you've installed `alx-folder-note`? I think you may installed only `alx-folder-note-folderv`component, and can you post a screenshot on AidenLx's Folder Note setting tab?

**Comment by anselmwang** [comment]
@aidenlx , thanks a lot for your quick response! It turns out to me my mistake. 
Now I have fully migrated from "Folder Note" to "alx-folder-note". Thanks a lot for creating this plugin!
