### ISSUE TITLE
Improve handling of loading folder-note-core API

### ISSUE THREAD

**Issue by meatbagger** [aidenlx/alx-folder-note#67]
The entire plugin is failing to initialize on a MacOS device and iOS device after having worked flawlessly for many weeks.

Plugin version: 0.16.0
MacOS Obsidian version: 0.14.2 (I use Insider builds)
iOS Obsidian version: 1.1.1 (48)

It appears the error gets logged somewhere but I cannot figure out where, I apologize. Happy to give further information. I don't use GitHub at all - my bad if I am doing something wrong.

Thank you for your very hard work on this great plugin.

**Comment by hsiktas** [comment]
I see this error in the dev tools console:
> Uncaught (in promise) Error: Failed to initialize alx-folder-note: Click here for more details
    at sr.get CoreApi [as CoreApi] (eval at <anonymous> (app.js:1:1444405), <anonymous>:46:20204)
    at Fi (eval at <anonymous> (app.js:1:1444405), <anonymous>:46:1524)
    at sr.eval (eval at <anonymous> (app.js:1:1444405), <anonymous>:47:83)
    at Generator.next (<anonymous>)
    at o (eval at <anonymous> (app.js:1:1444405), <anonymous>:6:972)

**Comment by aidenlx** [comment]
can you check the setting tab of aidenlx's folder note to see if folder note core is installed and enabled?

**Comment by hsiktas** [comment]
Does this look right to you?

https://user-images.githubusercontent.com/4571159/160394621-4251f3d6-974e-43b7-a74a-95d98737945b.mp4

**Comment by AmbushXXVI** [comment]
This is happening with me on PC as well, though the vault is stored on a google drive and also opened on MacOS as well. Core is installed.

**Comment by aidenlx** [comment]
I’m having trouble reproducing the issue… could you send the debug info (should be a command called `show debug info`) and upload the .obsidian config folder in zip file?

**Comment by AmbushXXVI** [comment]
SYSTEM INFO:
	Obsidian version: v0.13.33
	Installer version: v0.12.19
	Operating system: Windows 10 Pro 10.0.19044
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 14
	Plugins enabled: 13
		1: Table Extended
		2: Dataview
		3: Templater
		4: Admonition
		5: Find unlinked files and unresolved links
		6: Buttons
		7: Banners
		8: TTRPG Statblocks
		9: AidenLx's Folder Note
		10: Folder Note Core
		11: Automatically reveal active file
		12: Find and replace in selection
		13: Icon Shortcodes

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
[Ambush.obsidian.zip](https://github.com/aidenlx/alx-folder-note/files/8363456/Ambush.obsidian.zip)

**Comment by aidenlx** [comment]
@AmbushXXVI @meatbagger could you try disable and reenable aidenlx’s folder note to see if it still occurs?

**Comment by AmbushXXVI** [comment]
seems to have cleared for me

**Comment by meatbagger** [comment]
Hello - disabling and re-enabling the plugin on MacOS cleared the issue for both MacOS and iOS. The most basic of IT fixes alluded me, apparently. Thank you all.

**Comment by aidenlx** [comment]
v0.16.1 should handle the case which folder-note-core loads after this plugin properly
