### ISSUE TITLE
Option to not show underline in navigation for folders with "folder note"

### ISSUE THREAD

**Issue by JustSkiv** [aidenlx/alx-folder-note#72]
In original Folder Note plugin folders with "folder notes" and without it differ in color: folder with note is white and without it - gray (at least in the theme I use - Mininal).

It would be great to be able to choose how such folders are displayed. I don't like underline, especially when there are too many of them.

**Comment by aidenlx** [comment]
See here: https://github.com/aidenlx/alx-folder-note/issues/34#issuecomment-1061290056

**Comment by JustSkiv** [comment]
Thank you! This is exactly what I needed 👍
