### ISSUE TITLE
Failed to load plugin alx-folder-note

### ISSUE THREAD

**Issue by Chr9sG** [aidenlx/alx-folder-note#73]
This just started showing up today after I downloaded the latest update. Now the folder notes are showing up as a separate note inside the folder instead of being the folder itself.

**Comment by aidenlx** [comment]
can you upload the console log (see method below) and versions of both alx-folder-note and folder-note-core? also, a screenshot of the folder note's setting tab could be helpful. 

```
To check for errors, first open the developer tools by pressing Ctrl-Shift-I on Windows/Linux or Cmd-Opt-I on macOS, and then go to the "Console" tab. If you want to save the error to a log file, you can right click on the error and choose "Save as...".
```

**Comment by Chr9sG** [comment]
There is an error. Here is a screen shot.

![image](https://user-images.githubusercontent.com/97812598/163711883-ff540712-2ef6-49b8-a159-ecedc97a2728.png)

**Comment by Chr9sG** [comment]
AidenLx's Folder Note version 0.16.2
Folder Note Core version 1.3.4

**Comment by aidenlx** [comment]
Can you also provide the output of command “show debug info”?

**Comment by Chr9sG** [comment]
Sorry. I don't have any coding experience. Where (or how) do I do that?

A bit of additional info. If I delete the file from the plugin folder and copy and paste the prior version into the obsidian plugin folder (from my archived vault) it words fine. So it seems to be something unique to this last update.

**Comment by Chr9sG** [comment]
Is this what you mean?

![image](https://user-images.githubusercontent.com/97812598/163721077-b01e9d89-2a1d-4ca5-b418-fa52baa19ae4.png)

**Comment by Chr9sG** [comment]
Turned off all my plugins except for AidenLx's Folder Note and Folder Note Core and I get the same message. So it's not an issue with interacting with other plugins.

**Comment by aidenlx** [comment]
The show debug info command is the one inside command palette https://help.obsidian.md/Plugins/Command+palette

**Comment by Chr9sG** [comment]
Thanks. Here it is:

SYSTEM INFO:
	Obsidian version: v0.14.5
	Installer version: v0.12.19
	Operating system: Windows 10 Home 10.0.19044
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: on
	Base theme: light
	Community theme: none
	Snippets enabled: 2
	Safe mode: off
	Plugins installed: 13
	Plugins enabled: 13
		1: Admonition
		2: Dataview
		3: Dice Roller
		4: Fantasy Calendar
		5: Initiative Tracker
		6: Obsidian Leaflet
		7: Obsidian42 - BRAT
		8: Recent Files
		9: Second Window
		10: Sliding Panes (Andy's Mode)
		11: TTRPG Statblocks
		12: Folder Note Core
		13: AidenLx's Folder Note

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by aidenlx** [comment]
[归档.zip](https://github.com/aidenlx/alx-folder-note/files/8506791/default.zip)

can replacing with this version solve problem for you? (follow this to install: https://github.com/aidenlx/alx-folder-note#from-github)

**Comment by Chr9sG** [comment]
Yes! That solved the issue. Works fine now. Thanks. Will that be a new update?

**Comment by aidenlx** [comment]
sure, the update will be released shortly. before that, what error message exactly is showing up? and could you try dragging folder with underline to markdown note to see if the link is inserted? is there a `clipboard manager patched` message in console log?

**Comment by Chr9sG** [comment]
It flashes in the top right corner briefly. Here is the screen shot of it. 

![image](https://user-images.githubusercontent.com/97812598/163865934-f3d56f2c-d700-4039-9f68-c828291d6443.png)

**Comment by Chr9sG** [comment]
As to the other question - yes. Here is the screen shot.

![image](https://user-images.githubusercontent.com/97812598/163866288-7c1861d6-0e44-4612-87c4-1d6c6dea2b56.png)

**Comment by aidenlx** [comment]
okay, in v0.16.3 I've fixed compatibility issue with legacy editor, it should work as expected now.

**Comment by Chr9sG** [comment]
Thanks. Just updated and everything looks line. It's not posting the message anymore and the folder notes are working as expected. Thanks for the quick update.
