### ISSUE TITLE
Daily Stats plugin has stopped working

### ISSUE THREAD

**Issue by icegrim** [aidenlx/alx-folder-note#75]
Hi, the [Daily stats plugin](https://github.com/dhruvik7/obsidian-daily-stats) I am using, stopped working after the last update. Can no longer count words in folder notes. For normal notes, everything works fine. Can you do something about it or tell me how I can revert to the old version? Thanks

**Comment by aidenlx** [comment]
can you reproduce this in new(sandbox) vault? for old version, you can remove plugin and [manually install](https://github.com/aidenlx/alx-folder-note#from-github) the old version from GitHub Release
