### ISSUE TITLE
Is there any way to get folders in the folderv overview?

### ISSUE THREAD

**Issue by fakeharxy** [aidenlx/alx-folder-note#81]
As the title, I'm using folderv and it works great, but it would be nice to get the folder notes of any folders to make a chained hierarchy... is this possible?

**Comment by Kuiriel** [comment]
Would love it if this was added. I already love how folderv cards are smaller than regular headings so that you can actually see them instead of them taking up half the page.

**Comment by TristGit** [comment]
![image](https://user-images.githubusercontent.com/57966174/219907329-79ae8273-94c6-42e0-8628-69df80be74d4.png)
Would like this, too. This is the other Folder Note plugin. But it ONLY shows notes and there have been people asking for this for a year but he doesnt seem to want to.
